directory: /var/media/music
library: ~/media/music/tools/music.blb

format_item: $artist - $album - $track - $title ($genre)
format_album: $albumartist - $album [$original_year] ($genre)

pluginpath: ~/media/music/tools/
plugins: fetchart mbsync embedart info missing lyrics lastgenre check

art_filename: folder

ui:
  color: yes

threaded: yes
clutter: ['Thumbs.db', '.DS_Store', '*.log', '*.txt', '*.cue', '*.m3u', '*.sfv', '*.nfo']

asciify_paths: yes

import:
    write: yes
    move: yes
    resume: no
    incremental: no
    languages: ['en']
    default_action: 'skip'

match:
    preferred:
        countries: ['US', 'GB|UK', 'XW', 'XE']
        media: ['CD', 'Digital Media|File']
        original_year: yes

fetchart:
  # Pick only trusted filenames (cover_names)
  cautious: yes
  cover_names: front folder cover

paths:
    default: albums/$albumartist - $album [$original_year]%aunique{albumartist album original_year, albumtype original_year year label catalognum albumdisambig}/$track - $title
    comp: albums/$albumartist - $album [$original_year]%aunique{albumartist album original_year, albumtype original_year year label catalognum albumdisambig}/$track - $title
    singleton: non-albums/$artist/$original_year - $title

scrub:
    auto: no

lyrics:
    google_API_key: REPLACEME

lastgenre:
    fallback: 'Unknown'
    source: artist
    count: 3
    whitelist: ~/media/music/tools/genres.txt
    canonical: ~/media/music/tools/genres-tree.yaml

check:
    backup: no
