[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.zplug/init.zsh

# Aliases {{{

# Make ls colorful
alias ls="ls --color=auto"

# todo
alias t="$HOME/.bin/todo.sh"

# }}}

# Plugin Settings {{{

# FZF {{{
export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='
--color fg:242,bg:236,hl:65,fg+:15,bg+:239,hl+:108
--color info:108,prompt:109,spinner:108,pointer:168,marker:168
'
# }}}

# NVM {{{  

# Make sure nvm loads lazily
export NVM_LAZY_LOAD=true

# }}}

# }}}

# Plugins {{{

# Make my terminal beautiful
zplug "dracula/zsh", as:theme

# Make the ls options legible
zplug "liangguohuan/zsh-dircolors-solarized", as:plugin

# Give me some autocomplete options
zplug 'zsh-users/zsh-autosuggestions', as:plugin, from:github

# Add the node version manager plugin
zplug 'lukechilds/zsh-nvm', as:plugin, from:github

# Add the python version manager plugin
zplug "ayamnova/zsh-pyenv", as:plugin, from:github

# Warp Directory
zplug 'mfaerevaag/wd', as:command, use:"wd.sh", hook-load:"wd() { . $ZPLUG_REPOS/mfaerevaag/wd/wd.sh }"

zplug load

# }}}

# Environment Variables {{{

# PATH
export PATH=$HOME/.bin:$HOME/.local/bin:$PATH

# Change the color of ls output so it is light against the dark dracula background
export DIRCOLORTHEME='dircolors.ansi-light'

# }}}

# Keyboard mappings {{{

# map CAPS_LOCK to escape
setxkbmap -option caps:escape
# swap left alt and left ctrl
setxkbmap -option ctrl:swap_lalt_lctl

# }}}
