zmodload zsh/zprof
# Aliases {{{
alias t="$HOME/.bin/todo.sh"
# }}}
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# KEYBINDINGS {{{

# map CAPS_LOCK to escape
setxkbmap -option caps:escape
# swap left alt and left ctrl
setxkbmap -option ctrl:swap_lalt_lctl


# has command
# _has(){
#     command type "$1" > /dev/null 2>&1
# }

# Path to your oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

#Add my own custom bin to path
  export PATH=$HOME/.local/bin:$PATH
  export PATH=$HOME/bin:$PATH
  export PATH=$HOME/.bin:$PATH

# Make sure nvm loads lazily
export NVM_LAZY_LOAD=true

# ZPLUG

source ~/.zplug/init.zsh

# Get my dracula theme. Boo yeah!
zplug "dracula/zsh", as:theme

# Autocomplete

zplug 'zsh-users/zsh-autosuggestions', as:plugin, from:github

zplug 'joel-porquet/zsh-dircolors-solarized', as:plugin, from:github

zplug 'lukechilds/zsh-nvm', as:plugin, from:github

# Add npm completion options
zplug "lukechilds/zsh-better-npm-completion", as:plugin, from:github, defer:2

# Automatically install pyenv
#zplug "mattberther/zsh-pyenv", as:plugin, from:github
zplug "ayamnova/zsh-pyenv", as:plugin, from:github
# pyenv() {
#   eval "$(command pyenv init -)"
#   pyenv "$@"
# }

##### nvm (node version manager) #####
# placeholder nvm shell function
# On first use, it will set nvm up properly which will replace the `nvm`
# shell function with the real one
# nvm() {
#   if [[ -d '/usr/local/opt/nvm' ]]; then
#     NVM_DIR="/usr/local/opt/nvm"
#     export NVM_DIR
#     # shellcheck disable=SC1090
#     source "${NVM_DIR}/nvm.sh"
#     if [[ -e ~/.nvm/alias/default ]]; then
#       PATH="${PATH}:${HOME}.nvm/versions/node/$(cat ~/.nvm/alias/default)/bin"
#     fi
#     # invoke the real nvm function now
#     nvm "$@"
#   else
#     echo "nvm is not installed" >&2
#     return 1
#   fi
# }


#Add custom dircolors
  #eval $(dircolors -b ~/.dircolorsrc)
  #export LS_OPTIONS='--color=auto'

#Change dircolors to a legible color
# available options:
# 	dircolors.256dark, dircolors.ansi-dark 
# 	dircolors.ansi-light, dircolors.ansi-universal
#  export DIRCOLORTHEME='dircolors.ansi-dark'
export DIRCOLORTHEME='dircolors.ansi-light'

# Konsole Color Theme
#BASE16_SHELL=$HOME/.config/base16-shell/
#[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="dracula"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  dirhistory
  git-extras
  wd
  dirhistory
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# fzf + ag configuration
#if _has fzf && _has ag; then
export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='
--color fg:242,bg:236,hl:65,fg+:15,bg+:239,hl+:108
--color info:108,prompt:109,spinner:108,pointer:168,marker:168
'
#fi

# Anaconda configuration
# export PATH="/home/karsten/opt/anaconda3/bin":$PATH

zplug load

bindkey ' ' magic-space
