library: /var/music/tools/albums.blb
directory: /var/music

list_format_item: $artist - $album - $track - $title ($genre)
list_format_album: $albumartist - $album [$original_year] ($genre)

pluginpath: /var/music/tools/
plugins: fetchart mbsync mbcollection embedart info missing lyrics lastgenre check # scrub web bpd chroma

art_filename: folder

threaded: yes
color: yes
clutter: ['Thumbs.db', '.DS_Store', '*.log', '*.txt', '*.cue']

import:
    write: yes
    move: yes
    resume: no
    incremental: no
    languages: ['en']
    default_action: 'skip'

match:
    preferred:
        countries: ['US', 'GB|UK', 'XW']
        media: ['CD', 'Digital Media|File']
        original_year: yes

paths:
    default: albums/$albumartist - $album [$original_year]%aunique{albumartist album original_year, albumtype original_year year label catalognum albumdisambig}/$track - $title
    comp: albums/$albumartist - $album [$original_year]%aunique{albumartist album original_year, albumtype original_year year label catalognum albumdisambig}/$track - $title
    singleton: non-albums/$artist/$original_year - $title

musicbrainz:
    user: fortes
    pass: REPLACEME

scrub:
    auto: no

lyrics:
    google_API_key: REPLACEME

lastgenre:
    fallback: 'Unknown'
    source: artist
    count: 3
    whitelist: /var/music/tools/genres.txt
    canonical: /var/music/tools/genres-tree.yaml

check:
    backup: no
