directory: /var/media/music
library: ~/media/music/tools/music.blb

format_item: $artist - $album - $track - $title ($genre)
format_album: "[$original_year] $albumartist - $album ($genre)"

pluginpath: ~/media/music/tools/
plugins: fetchart mbsync embedart info missing lyrics lastgenre badfiles types replaygain edit

art_filename: folder

ui:
  color: yes

threaded: yes
clutter: ['Thumbs.db', '.DS_Store', '*.log', '*.txt', '*.cue', '*.m3u', '*.sfv', '*.nfo']

asciify_paths: yes
max_filename_length: 120

import:
  write: yes
  move: yes
  resume: no
  incremental: no
  languages: ['en']
  default_action: 'skip'

match:
  preferred:
    countries: ['US', 'GB|UK', 'XW', 'XE']
    media: ['CD', 'Digital Media|File']
    original_year: yes

fetchart:
  # Pick only trusted filenames (cover_names)
  cautious: yes
  cover_names: front folder cover

paths:
  default: albums/$albumartist - [$original_year] $album%aunique{albumartist album original_year, albumtype albumdisambig year label catalognum}/$track - $title
  comp: albums/$albumartist - [$original_year] $album%aunique{albumartist album original_year, albumtype albumdisambig year label catalognum}/$track - $title
  singleton: non-albums/$artist/[$original_year] $title

lyrics:
  auto: yes

lastgenre:
  fallback: 'Unknown'
  source: artist
  count: 3
  whitelist: ~/media/music/tools/genres.txt
  canonical: ~/media/music/tools/genres-tree.yaml

types:
  rating: int

replaygain:
  auto: yes
